version: '3.8'

services:
  db_library:
    container_name: db_library
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_library
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin

    app_library:
      image:
